import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Student, OptionList, ScoredCollege } from '../types';

/**
 * Generate HTML for PDF
 */
function generatePDFHTML(student: Student, optionList: OptionList): string {
    const formatCollegeRow = (college: ScoredCollege, index: number) => `
    <tr>
      <td>${index + 1}</td>
      <td>${college.collegeName}</td>
      <td>${college.courseName}</td>
      <td>${college.category}</td>
      <td>${college.cutoffRank.toLocaleString()}</td>
      <td>${(college.probability * 100).toFixed(0)}%</td>
    </tr>
  `;

    return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Option Entry List - ${student.name}</title>
        <style>
          body {
            font-family: 'Arial', sans-serif;
            margin: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #6366F1;
            padding-bottom: 20px;
          }
          h1 {
            color: #6366F1;
            margin: 0;
          }
          .student-info {
            background: #F3F4F6;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
          }
          .student-info p {
            margin: 5px 0;
          }
          .section {
            margin-bottom: 30px;
          }
          .section-header {
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 10px;
            color: white;
            font-weight: bold;
          }
          .safe { background: #10B981; }
          .target { background: #F59E0B; }
          .reach { background: #EF4444; }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
          }
          th {
            background-color: #6366F1;
            color: white;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #ddd;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>BharatMinds AI Counsellor</h1>
          <h2>Option Entry List</h2>
        </div>
        
        <div class="student-info">
          <p><strong>Student Name:</strong> ${student.name}</p>
          <p><strong>KCET Rank:</strong> ${student.rank.toLocaleString()}</p>
          <p><strong>Category:</strong> ${student.baseCategory}</p>
          <p><strong>Eligible Categories:</strong> ${student.eligibleCategories.join(', ')}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-IN')}</p>
        </div>
        
        <div class="section">
          <div class="section-header safe">SAFE OPTIONS (80-95% Probability)</div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>College</th>
                <th>Branch</th>
                <th>Category</th>
                <th>Cutoff</th>
                <th>Probability</th>
              </tr>
            </thead>
            <tbody>
              ${optionList.safe.map((c, i) => formatCollegeRow(c, i)).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="section">
          <div class="section-header target">TARGET OPTIONS (40-80% Probability)</div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>College</th>
                <th>Branch</th>
                <th>Category</th>
                <th>Cutoff</th>
                <th>Probability</th>
              </tr>
            </thead>
            <tbody>
              ${optionList.target.map((c, i) => formatCollegeRow(c, i)).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="section">
          <div class="section-header reach">REACH OPTIONS (20-40% Probability)</div>
          <table>
            <thead>
              <tr>
                <th>#</th>
                <th>College</th>
                <th>Branch</th>
                <th>Category</th>
                <th>Cutoff</th>
                <th>Probability</th>
              </tr>
            </thead>
            <tbody>
              ${optionList.reach.map((c, i) => formatCollegeRow(c, i)).join('')}
            </tbody>
          </table>
        </div>
        
        <div class="footer">
          <p><strong>Generated by BharatMinds AI Counsellor</strong></p>
          <p>This list is based on KCET 2024 Round 1 cutoff data</p>
          <p>Actual cutoffs may vary. Use this as a guide for your option entry.</p>
        </div>
      </body>
    </html>
  `;
}

/**
 * Generate and share PDF
 */
export async function generateAndSharePDF(
    student: Student,
    optionList: OptionList
): Promise<void> {
    try {
        const html = generatePDFHTML(student, optionList);

        const { uri } = await Print.printToFileAsync({
            html,
            base64: false
        });

        if (await Sharing.isAvailableAsync()) {
            await Sharing.shareAsync(uri, {
                mimeType: 'application/pdf',
                dialogTitle: 'Share Option List',
                UTI: 'com.adobe.pdf'
            });
        } else {
            console.log('Sharing is not available');
        }
    } catch (error) {
        console.error('Error generating PDF:', error);
        throw error;
    }
}
